# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\berfi\OneDrive\Masaüstü\pyqt5ödev\fixer.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests

url = "http://data.fixer.io/api/latest?access_key=f75b94cc38f92a362fc3b61ddd2928e5"
response = requests.get(url)
veri = response.json()


class Ui_Form(object):
    def setupUi(self, Form):
        url = "http://data.fixer.io/api/latest?access_key=f75b94cc38f92a362fc3b61ddd2928e5"
        response = requests.get(url)
        self.veri = response.json()
        Form.setObjectName("Form")
        Form.resize(1050, 783)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 40, 631, 691))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.exchange = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.exchange.setMaximumSize(QtCore.QSize(629, 16777215))
        self.exchange.setScaledContents(False)
        self.exchange.setWordWrap(False)
        self.exchange.setIndent(-15)
        self.exchange.setOpenExternalLinks(False)
        self.exchange.setObjectName("exchange")
        self.verticalLayout.addWidget(self.exchange, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("C:\\Users\\berfi\\OneDrive\Masaüstü\\pyqt5 ile dolar kuru\\media\\Klavyemde-dolar-işareti-yapamıyorum-1.jpg"))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.radioButton_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_6.setAutoRepeat(True)
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_8.addWidget(self.radioButton_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("C:\\Users\\berfi\\OneDrive\\Masaüstü\yazılım\\PyQt5\\pyqt5ödev\\turk-lirasi.png"))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("C:\\Users\\berfi\\OneDrive\\Masaüstü\\pyqt5 ile dolar kuru\\media\\indir.png"))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_5.addWidget(self.radioButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")

        self.horizontalLayout_10.addWidget(self.comboBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setText("")
        self.label_11.setPixmap(
            QtGui.QPixmap("C:\\Users\\berfi\\OneDrive\Masaüstü\\pyqt5 ile dolar kuru\\media\\Klavyemde-dolar-işareti-yapamıyorum-1.jpg"))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_5.setCheckable(True)
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setAutoRepeat(True)
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_7.addWidget(self.radioButton_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("C:\\Users\\berfi\\OneDrive\\Masaüstü\\pyqt5 ile dolar kuru\\media\\turk-lirasi.png"))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_4.addWidget(self.radioButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("C:\\Users\\berfi\\OneDrive\Masaüstü\\pyqt5 ile dolar kuru\\media\\indir.png"))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_6.addWidget(self.radioButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")

        self.horizontalLayout_9.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(409, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit, 0, QtCore.Qt.AlignVCenter)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.sonuc = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sonuc.setObjectName("sonuc")
        self.verticalLayout.addWidget(self.sonuc)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.veris = 1
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.exchange.setText(_translate("Form",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">EXCHANGE</span></p></body></html>"))
        self.label_3.setText(_translate("Form",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">First Currency</span></p></body></html>"))
        self.radioButton_6.setText(_translate("Form", "USD"))
        self.radioButton.setText(_translate("Form", "TRY"))
        self.radioButton_3.setText(_translate("Form", "EUR"))
        self.label_20.setText(_translate("Form", "Another:"))
        for i in self.veri["rates"]:
            self.comboBox_2.addItem(i)

        self.label_4.setText(_translate("Form",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Second Currency</span></p></body></html>"))
        self.radioButton_5.setText(_translate("Form", "USD"))
        self.radioButton_2.setText(_translate("Form", "TRY"))
        self.radioButton_4.setText(_translate("Form", "EUR"))
        self.label_19.setText(_translate("Form", "Another:"))
        for i in self.veri["rates"]:
            self.comboBox.addItem(i)

        self.pushButton.setText(_translate("Form", "Contunie"))
        self.label_5.setText(_translate("Form", "Amount:"))
        self.label_6.setText(_translate("Form", "Choose"))
        self.pushButton_2.setText(_translate("Form", "Calculate"))
        self.sonuc.setText(_translate("Form",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Result</span></p></body></html>"))
        self.first_currency = ""
        self.second_currency = ""
        self.pushButton.clicked.connect(self.cont)
        self.radioButton.clicked.connect(self.go)
        self.radioButton_3.clicked.connect(self.go)
        self.radioButton_6.clicked.connect(self.go)
        self.radioButton_5.clicked.connect(self.go1)
        self.radioButton_2.clicked.connect(self.go1)
        self.radioButton_4.clicked.connect(self.go1)
        self.pushButton_2.clicked.connect(self.calculate)

    def go(self):
        self.sender = self.radioButton.sender()
        self.sender = self.radioButton_3.sender()
        self.sender = self.radioButton_6.sender()
        if self.sender.text() == "USD" or self.sender.text() == "TRY" or self.sender.text() == "EUR":
            self.first_currency = self.sender.text()
            assert isinstance(self.first_currency, object)


    def go1(self):

        self.sender1 = self.radioButton_5.sender()
        self.sender1 = self.radioButton_2.sender()
        self.sender1 = self.radioButton_4.sender()
        if self.sender.text() == "USD" or self.sender.text() == "TRY" or self.sender.text() == "EUR":
            self.second_currency = self.sender1.text()



    def cont(self):


        if self.first_currency=="":

            self.first_currency = self.comboBox_2.currentText()


        if self.second_currency=="":

            self.second_currency = self.comboBox.currentText()

        self.label_6.setText(self.first_currency)
        print(self.first_currency, self.second_currency)



    def calculate(self):

        if self.first_currency == "EUR":

            amount = self.lineEdit.text()
            b = self.veri["rates"][self.second_currency]

            self.a = (float(b) * float(amount))

            self.sonuc.setText(str(self.a) + " " + self.second_currency)

        elif self.first_currency in self.veri["rates"]:
            a = self.veri["rates"][self.first_currency]
            b = self.veri["rates"][self.second_currency]
            amount = self.lineEdit.text()
            b = (float(b) / float(a) * float(amount))

            self.sonuc.setText(str(b) + " " + self.second_currency)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
